
= Module 05: OpenShift Virtualization in the Cloud

include::vars.adoc[]

== Introduction

Red Hatのクラウドパートナーの力を活用することで、お客様は真のハイブリッド環境へOpenShift Virtualizationのデプロイを拡張できます。OpenShift Virtualizationは、Amazon Web Services（AWS）、Microsoft Azure、Google Cloud、IBM Cloud、およびOracle Cloud Infrastructureを含む主要なパブリッククラウドプロバイダーでサポートされており、組織にとって最も合理的な場所でワークロードを実行できる柔軟性を提供します。

このモジュールは主に座学（解説）中心ですが、これらのクラウドプラットフォーム上で動作するOpenShift Virtualizationを紹介するビデオデモやインタラクティブデモが含まれています。 +
クラウドでの利用可能性は、単一の一貫したプラットフォーム上で、クラウドネイティブ・アプリケーションと並行して仮想マシンを移行、モダナイズ、および運用できるようにすることで、モダナイゼーションにおいて重要な役割を果たします。仮想化ワークロードを選択したクラウドプロバイダーに拡張することで、お客様は、弾力的なスケール（伸縮性）、迅速なプロビジョニング、および一元化された管理と共同サポートによる運用の簡素化など、最初の導入動機となった多くの課題に対処できます。

また、クラウドインフラストラクチャ上でOpenShift Virtualizationを実行することは、リソースの最適化（ライトサイジング）、柔軟な利用モデルやコミットメントベースの料金モデルの活用、オンプレミスハードウェアの維持に伴うオーバーヘッドの削減を可能にし、コスト最適化戦略をサポートします。私たちが提携している各クラウドプロバイダーの詳細、およびそれらがどのようにOpenShift Virtualizationをサポートしているかについては、以下のセクションを参照してください。

== Amazon Web Services

Red Hat OpenShift Virtualizationは、Amazon Web Services（AWS）における自主管理型のRed Hat OpenShift、および完全管理型の https://www.redhat.com/en/technologies/cloud-computing/openshift/aws[Red Hat OpenShift on AWS (ROSA)^] クラスターの双方で *一般利用可能（Generally Available: GA）* になっています。Virtualization Operatorをインストールし、クラスターにベアメタルのコンピュートノードを追加するだけで簡単に利用できます。

*Video Demo: Configuring a ROSA cluster to run OpenShift Virtualization*

++++
<iframe width="800" height="480" src="https://www.youtube.com/embed/wBtY3tvjtIU" title="Configuring OpenShift Virtualization to run on Red Hat OpenShift Service on AWS" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
++++

*Video Demo: Deploying Virtual Machines in OpenShift Virtualization on ROSA*

++++
<iframe width="800" height="480" src="https://www.youtube.com/embed/7EpmmUIhQ7c" title="Deploying Virtual machines in OpenShift Virtualization on Red Hat OpenShift Service on AWS" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
++++

*Lightboard Video: Optimizing Cloud Costs with ROSA*

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/tPYztiqMO58?si=tl_qYGELpxtpW4IK" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
++++


== Google Cloud

Red Hat OpenShift Virtualizationは、 https://www.redhat.com/en/blog/red-hat-openshift-virtualization-google-cloud[Google Cloud^]  で現在 *テクノロジープレビュー（Technology Preview）* として利用可能です。

*Arcade Interactive Demo: Deploy Virtual Machines in OpenShift Virtualization on Red Hat OpenShift Dedicated*
 
++++
<!--ARCADE EMBED START--><div style="position: relative; padding-bottom: calc(60.8805% + 41px); height: 0px; width: 100%;"><iframe src="https://demo.arcade.software/HleIaKgn1Iuf9SrJSt3S?embed&embed_mobile=tab&embed_desktop=inline&show_copy_link=true" title="Deploy Virtual Machines in OpenShift Virtualization on Red Hat OpenShift Dedicated" frameborder="0" loading="lazy" webkitallowfullscreen mozallowfullscreen allowfullscreen allow="clipboard-write" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; color-scheme: light;" ></iframe></div><!--ARCADE EMBED END-->
++++

== IBM Cloud

Red Hat OpenShift Virtualizationは、 https://www.ibm.com/new/announcements/red-hat-openshift-virtualization-is-now-available-on-ibm-cloud2[IBM Cloud^] でも *一般利用可能（Generally Available: GA）* になりました。

== Microsoft Azure

Red Hat OpenShift Virtualizationは、完全管理型ソリューションである https://www.redhat.com/en/technologies/cloud-computing/openshift/azure[Azure Red Hat OpenShift (ARO)^] の一部として、 https://learn.microsoft.com/en-us/azure/openshift/howto-create-openshift-virtualization[Microsoft Azure^] でも *一般利用可能（Generally Available: GA）* になりました。

*Arcade Interactive Demo: Azure Red Hat OpenShift Virtualization Demo*

++++
<!--ARCADE EMBED START--><div style="position: relative; padding-bottom: calc(56.25% + 41px); height: 0px; width: 100%;"><iframe src="https://demo.arcade.software/qMIbsgMch6Hrhz5ZI0Fr?embed&embed_mobile=tab&embed_desktop=inline&show_copy_link=true" title="Azure Red Hat Openshift Virtualization Demo" frameborder="0" loading="lazy" webkitallowfullscreen mozallowfullscreen allowfullscreen allow="clipboard-write" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; color-scheme: light;" ></iframe></div><!--ARCADE EMBED END-->
++++

*Arcade Interactive Demo: Effortless VM Deployment with Azure Red Hat OpenShift*

++++
<!--ARCADE EMBED START--><div style="position: relative; padding-bottom: calc(53.5053% + 41px); height: 0px; width: 100%;"><iframe src="https://demo.arcade.software/ZcUp0s4iubfGRYc7GZUY?embed&embed_mobile=tab&embed_desktop=inline&show_copy_link=true" title="Effortless VM Deployment with Azure Red HatOpenShift" frameborder="0" loading="lazy" webkitallowfullscreen mozallowfullscreen allowfullscreen allow="clipboard-write" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; color-scheme: light;" ></iframe></div><!--ARCADE EMBED END-->
++++

== Oracle Cloud

Red Hat OpenShift Virtualizationは、 https://blogs.oracle.com/cloud-infrastructure/red-hat-openshift-virtualization-available-on-oci[Oracle Cloud^] でも *一般利用可能（Generally Available: GA）* になりました。

== Conclusion

クラウドパートナー環境でRed Hat OpenShift Virtualizationを利用できるようになったことで、お客様はデータセンターを仮想マシンとコンテナの双方に対応した完全なハイブリッドシナリオへと拡張できます。これにより、複数のリージョンやアベイラビリティゾーンにまたがる耐障害性の高いアプリケーションや冗長インフラストラクチャを実現し、サービスを常に利用可能な状態に保つことができます。

さらに、Red Hat OpenShift Cloud Servicesは、デプロイと管理を簡素化することで運用をモダンに進化させ、お客様がより少ない運用オーバーヘッドで迅速に立ち上げ、実行できるように支援します。
