
= Module 04: Self-service VM Provisioning with Developer Hub

include::vars.adoc[]

## About Red Hat Developer Hub（Red Hat Developer Hubについて）

Red Hat Developer Hub (RHDH) は、ソフトウェア開発プロセスを簡素化・合理化するために設計された、エンタープライズグレードの社内開発者向けポータル（IDP: Internal Developer Portal）です。Red Hat OpenShift Container Platformと組み合わせることで、RHDHはプラットフォームエンジニアリングチームがカスタマイズされたポータルを作成できるようにし、開発者の生産性を向上させ、オンボーディング（環境適応）を加速し、迅速なアプリケーション配信を可能にします。

摩擦や複雑さを軽減することで、RHDHは開発者がエンタープライズクラスのベストプラクティスを遵守しながら、高品質なコードの記述に集中できるようにします。

RHDHは、ソフトウェアテンプレート、事前設計されたソリューション、および動的プラグインを集中管理型のプラットフォームに統合し、統合された環境で運用チームと開発チームの双方に最適なソリューションを提供します。

### Key Features（主な機能）

*Centralized Dashboard（中央管理ダッシュボード）*
開発ツール、CI/CDパイプライン、API、監視ツール、およびドキュメントにアクセスするための単一のインターフェースを提供します。Git、OpenShift、Kubernetes、JIRAなどのシステムと統合されています。

*Dynamic Plugins（動的プラグイン）*
システムを停止することなく、プラグインを動的に追加、更新、または削除できます。Tekton、GitOps、Nexus Repository、JFrog Artifactoryなどの一般的なプラグインがサポートされており、Red Hatによって検証されています。

*Software Templates（ソフトウェアテンプレート）*
リポジトリのセットアップ、変数の挿入、本番パイプラインの作成などのタスクを自動化することで、開発プロセスを簡素化します。

*Role-Based Access Control（RBAC：ロールベースアクセス制御）*
組織のニーズに合わせた強固なセキュリティ権限でユーザーアクセスを管理します。

*Scalability（拡張性）*
同じツールやサービスへのアクセスを維持しながら、拡大するチームやアプリケーションをサポートします。

*Configuration Management（構成管理）*
集中管理されたリポジトリにより同期されたアップデートが保証され、バージョン管理と環境構成が向上します。

## Arcade（デモ画面）

++++
<!--ARCADE EMBED START--><div style="position: relative; padding-bottom: calc(48.645833333333336% + 41px); height: 0; width: 100%;"><iframe src="https://demo.arcade.software/Dtucjw9jV2mRAGFAi420?embed&embed_mobile=tab&embed_desktop=inline&show_copy_link=true" title="Self-service provisioning VMs with Red Hat Developer Hub" frameborder="0" loading="lazy" webkitallowfullscreen mozallowfullscreen allowfullscreen allow="clipboard-write" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; color-scheme: light;" ></iframe></div><!--ARCADE EMBED END-->
++++
